### ISSUE TITLE
what's ur issue

### ISSUE THREAD

**Issue by ZachTapia** [clucero36/jetboats#1]

**Comment by clucero36** [comment]
Currently, promise.all returns 3 http responses. 

Doesn't awaiting 3 consecutive times defeat the purpose of a promise.all

    const [ productsRes, faqsRes, reviewsRes ] = await Promise.all([
      productsPromise,
      faqsPromise,
      reviewsPromise
    ]);

products = await proudctsRes.json();
faqs = await faqsRes.json();
reviews = await reviewsRes.json();

**Comment by ZachTapia** [comment]
# Benefits of using Promise.all([p1,p2,p3])
If any of the 3 promises fail, then Promise.all will fail. So if you need to ensure all 3 resolve successfully this is useful.

> Currently, promise.all returns 3 http responses.

This is intended. 

> Doesn't awaiting 3 consecutive times defeat the purpose of a promise.all

No, with promise.all() all promises are started concurrently, so it's faster than sequential awaits.
await p1;
-some amount of time passes-
await p2;
-some amount of time passes-
await p3;
-done-

**Comment by clucero36** [comment]
Yes, this all makes sense. 

In order to grab the needed Data from the http responses I need to await response.json()

**Comment by clucero36** [comment]
> Yes, this all makes sense.
> 
> In order to grab the needed data from the http responses I need to await response.json() 3 times.

**Comment by ZachTapia** [comment]
You looking for some weird shit like this.

`const allPromisesResolvedAsJSON = await Promise.all([awaitPromiseAndThenAwaitResponseJSON(p1), awaitPromiseAndThenAwaitResponseJSON(p2),awaitPromiseAndThenAwaitResponseJSON(p3)]);`

always doin too much zzzz

**Comment by ZachTapia** [comment]
always doin too much zzzz

**Comment by ZachTapia** [comment]
```
const solve = async () => {
   const projects = currentUserProjectIDs.map((p) => {
     return callAPI(`/projects/${p}`)
        .then((r) => {
          return r.json();
        });
    });
    return Promise.all(projects);
  };

const prj = await solve();
```
type shit
